(function () {
  "use strict";

  window.PLACES = [
    {
      id: "protokoll-yeonhui",
      name: "Protokoll",
      koreanName: "프로토콜 연희점",
      category: "Coffee / Roastery",
      area: "延禧洞 Yeonhui",
      areaSlug: "yeonhui",
      district: "西大門區 Seodaemun-gu",
      address: "109 Yeonhui-ro, Seodaemun-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/프로토콜%20연희점",
      openingHours: null,
      notes: "原豆烘焙咖啡廳",
      tags: ["coffee", "roastery", "yeonhui"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "house-of-vinyl-yeonhui",
      name: "House of Vinyl Yeonhui",
      koreanName: "하우스오브바이닐 연희점",
      category: "Vinyl / Coffee",
      area: "延禧洞 Yeonhui",
      areaSlug: "yeonhui",
      district: "西大門區 Seodaemun-gu",
      address: "17-43 Yeonhuimat-ro, Seodaemun-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/하우스오브바이닐%20연희점",
      openingHours: null,
      notes: "黑膠唱片咖啡廳",
      tags: ["vinyl", "coffee", "yeonhui"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "sway-coffee-station",
      name: "Sway Coffee Station",
      koreanName: "스웨이커피스테이션",
      category: "Vinyl / Coffee",
      area: "延禧洞 Yeonhui",
      areaSlug: "yeonhui",
      district: "西大門區 Seodaemun-gu",
      address: "61 Yeonhui-ro 11-gil, Seodaemun-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/스웨이커피스테이션",
      openingHours: null,
      notes: "黑膠唱片咖啡廳",
      tags: ["vinyl", "coffee", "yeonhui"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "house-of-vinyl-yeonnam",
      name: "House of Vinyl Yeonnam",
      koreanName: "하우스오브바이닐 연남",
      category: "Vinyl / Coffee",
      area: "延南洞 Yeonnam",
      areaSlug: "yeonnam",
      district: "麻浦區 Mapo-gu",
      address: "230 Donggyo-ro, Mapo-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/하우스오브바이닐%20연남",
      openingHours: null,
      notes: null,
      tags: ["vinyl", "coffee", "yeonnam"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "house-of-vinyl-mangwon",
      name: "House of Vinyl Mangwon",
      koreanName: "하우스오브바이닐 망원점",
      category: "Vinyl / Coffee",
      area: "望遠洞 Mangwon",
      areaSlug: "mangwon",
      district: "麻浦區 Mapo-gu",
      address: "23 Huiujeong-ro 16-gil, Mapo-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/하우스오브바이닐%20망원점",
      openingHours: null,
      notes: null,
      tags: ["vinyl", "coffee", "mangwon"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "fritz-dohwa",
      name: "Fritz Coffee Company Dohwa",
      koreanName: "프릳츠 도화",
      category: "Coffee / Bakery / Roastery",
      area: "孔德 / 桃花洞 Gongdeok",
      areaSlug: "gongdeok",
      district: "麻浦區 Mapo-gu",
      address: "17 Saechang-ro 2-gil, Mapo-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/프릳츠%20도화",
      openingHours: null,
      notes: null,
      tags: ["coffee", "bakery", "roastery", "fritz"],
      brand: "Fritz Coffee Company",
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "33apartment",
      name: "33apartment",
      koreanName: "33apartment",
      category: "Coffee",
      area: "西村 / 景福宮 Seochon",
      areaSlug: "seochon",
      district: "鐘路區 Jongno-gu",
      address: "21-16 Jahamun-ro 11-gil, Jongno-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/33apartment%20서울",
      openingHours: null,
      notes: null,
      tags: ["coffee", "seochon"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "fritz-wonseo",
      name: "Fritz Coffee Company Wonseo",
      koreanName: "프릳츠 원서",
      category: "Coffee / Bakery / Roastery",
      area: "苑西洞 / 昌德宮 Wonseo",
      areaSlug: "wonseo",
      district: "鐘路區 Jongno-gu",
      address: "83 Yulgok-ro, Jongno-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/프릳츠%20원서",
      openingHours: null,
      notes: null,
      tags: ["coffee", "bakery", "fritz", "changdeokgung"],
      brand: "Fritz Coffee Company",
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "fritz-dongnimmun",
      name: "Fritz Coffee Company Dongnimmun",
      koreanName: "프릳츠 독립문",
      category: "Coffee / Bakery / Roastery",
      area: "獨立門 Dongnimmun",
      areaSlug: "dongnimmun",
      district: "鐘路區 Jongno-gu",
      address: "24-1 Tongil-ro 12-gil, Jongno-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/프릳츠%20독립문",
      openingHours: null,
      notes: null,
      tags: ["coffee", "bakery", "fritz"],
      brand: "Fritz Coffee Company",
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "stereophonic-sound",
      name: "Stereophonic Sound",
      koreanName: "Stereophonic Sound",
      category: "Music / Coffee",
      area: "獎忠洞 / 東大入口 Jangchung",
      areaSlug: "jangchung",
      district: "中區 Jung-gu",
      address: "218 Dongho-ro, Jung-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/스테레오포닉%20사운드%20서울",
      openingHours: null,
      notes: null,
      tags: ["music", "coffee", "jangchung"],
      brand: null,
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "fritz-jangchung",
      name: "Fritz Coffee Company Jangchung",
      koreanName: "프릳츠 장충",
      category: "Coffee / Bakery / Roastery",
      area: "獎忠洞 / 東大入口 Jangchung",
      areaSlug: "jangchung",
      district: "中區 Jung-gu",
      address: "11 Dongho-ro 24-gil, Jung-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/프릳츠%20장충",
      openingHours: null,
      notes: null,
      tags: ["coffee", "bakery", "fritz", "jangchung"],
      brand: "Fritz Coffee Company",
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "hybe-fritz",
      name: "HYBE Fritz",
      koreanName: "프릳츠 HYBE",
      category: "Coffee",
      area: "龍山 Yongsan",
      areaSlug: "yongsan",
      district: "龍山區 Yongsan-gu",
      address: "42 Hangang-daero, Yongsan-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/HYBE%20프릳츠",
      openingHours: null,
      notes: null,
      tags: ["coffee", "fritz", "yongsan"],
      brand: "Fritz Coffee Company",
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "fritz-yangjae",
      name: "Fritz Coffee Company Yangjae",
      koreanName: "프릳츠 양재",
      category: "Coffee / Bakery / Roastery",
      area: "良才 / 江南 Yangjae",
      areaSlug: "yangjae",
      district: "瑞草區 Seocho-gu",
      address: "24-11 Gangnam-daero 37-gil, Seocho-gu, Seoul",
      naverMapUrl: "https://map.naver.com/p/search/프릳츠%20양재",
      openingHours: null,
      notes: null,
      tags: ["coffee", "bakery", "fritz", "gangnam"],
      brand: "Fritz Coffee Company",
      city: "Seoul",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    },
    {
      id: "fritz-seongsan",
      name: "Fritz Coffee Company Seongsan",
      koreanName: "프릳츠 성산",
      category: "Coffee / Bakery / Roastery",
      area: "城山 Seongsan",
      areaSlug: "seongsan",
      district: "Seogwipo-si",
      address: "222 Ilchul-ro, Seongsan-eup, Seogwipo-si, Jeju-do",
      naverMapUrl: "https://map.naver.com/p/search/프릳츠%20성산",
      openingHours: null,
      notes: "不在首爾",
      tags: ["coffee", "bakery", "fritz", "jeju"],
      brand: "Fritz Coffee Company",
      city: "Jeju",
      country: "South Korea",
      active: true,
      latitude: null,
      longitude: null
    }
  ];
})();
